trigger:
- master

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: 'ubuntu-latest'

variables:
  CI: true

jobs:
#
# Backend Build
#
- job: backend_build
  displayName: "Backend build"

  steps:
  - script: |
      yarn install
    displayName: 'Build backend'

#
# Frontend Build
#
- job: frontend_build
  displayName: "Frontend build"

  steps:
  - script: |
      cd client
      yarn install
      yarn build

#
# Backend Tests
#
- job: test_backend
  displayName: "Backend tests"

  steps:
    - script: cd $(Build.SourcesDirectory) && yarn install &&  yarn test --ci
      displayName: "Install node_modules and run tests"

#
# Frontend Tests
#
- job: test_frontend
  displayName: "Frontend tests"

  steps:
    - script: cd $(Build.SourcesDirectory)/client && yarn install &&  yarn test --ci
      displayName: "Install node_modules and run tests"