trigger:
- master

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: 'ubuntu-latest'

variables:
  CI: true

jobs:
#
# Backend Tests
#
- job: test_backend
  displayName: "Fawkes Back-end Tests"
  steps:
    - script: |
        cd $(Build.SourcesDirectory)
        yarn install --frozen-lockfile
        yarn test --ci
      displayName: "Install node_modules and run tests"

#
# Frontend Tests
#
- job: test_frontend
  displayName: "Fawkes Front-end Tests"
  steps:
    - script: |
        cd $(Build.SourcesDirectory)/client
        yarn install --frozen-lockfile
        yarn test --ci
      displayName: "Install node_modules and run tests"

#
# Build and Package Release
#
- job: package_release
  displayName: "Build and Package Release"
  dependsOn:
  - test_frontend
  - test_backend
  condition: succeeded()

  steps:
    - script: |
        cd $(Build.SourcesDirectory)/client
        yarn install --frozen-lockfile
        yarn build
      displayName: "Build the React app"

    - script: |
        cd $(Build.SourcesDirectory)
        yarn install --frozen-lockfile
        yarn build
      displayName: "Build the Express server"

    - script: |
        cd $(Build.SourcesDirectory)
        yarn run bundle
      displayName: "Bundle the React app and Express server into a single artifact"

    # - task: CopyFiles@2
    #   inputs:
    #     Contents: 'fawkes-bundle.zip'
    #     TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: "Publish the Fawkes artifact"
      inputs: 
        pathToPublish: '$(Build.SourcesDirectory)/fawkes-bundle.zip'
        # pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
        ArtifactName: 'www' # output artifact named www
