version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      # maybe install yarn here
  pre_build:
    commands:
      - yarn install --frozen-lockfile
      - cd client
      - yarn install --frozen-lockfile
  build:
    commands:
      - yarn build
      - cd ../
      - yarn build

artifacts:
  files:
    - dist/**/*
    - client/build/**/*
    - .ebextensions/**/*
    - .elasticbeanstalk/**/*
    - ormconfig.js
    - package.json