#!/bin/bash

# clear out existing client model entities
rm -rf client/src/entity

# copy all model entities from server to client
cp -r src/entity client/src/

# Add comment to each model entity file warning devs against editing them directly
FILES=$(find client/src/entity | grep .ts)
for f in $FILES; do
    sed -i '1i/**\nDO NOT EDIT THIS FILE!!!!!\nIT IS COPIED FROM THE ROOT src/entity FOLDER\nTO UPDATE ENTITY MODEL DEFINITIONS, MAKE CHANGES TO THE FILES IN src/entity,\nAND THEN RUN ./copy-models-to-client.sh FROM ROOT DIR\n**/' $f
done
