version: '3.2'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: TestPassword1
      ACCEPT_EULA: Y
    ports:
      - 5002:1433

  winged-keys-db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: TestPassword1
      ACCEPT_EULA: Y
    ports:
      - 5051:1433
  winged-keys:
    build:
      context: .
      dockerfile: ./winged-keys/Dockerfile
    environment:
      ConnectionStrings__WINGEDKEYS: Server=winged-keys-db;Database=master;User=sa;Password=TestPassword1
    volumes:
      - ./winged-keys/src/WingedKeys:/app/src/WingedKeys:cached
      - ./winged-keys/entrypoint.sh:/entrypoint.sh
    working_dir: /app/src/WingedKeys
    ports:
      - 5050:5050
    entrypoint:
      - sh
      - /entrypoint.sh
    depends_on:
      - winged-keys-db
