version: 2.1

jobs:
  install:
    docker:
      - image: circleci/node@3.0.0
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: cd client
      - run: yarn install --frozen-lockfile --network-concurrency 1
  build:
    docker:
      - image: circleci/node@3.0.0
    steps:
      - run: yarn build
      - run: cd ../
      - run: yarn build
  test:
    docker:
      - image: circleci/node@3.0.0
    steps:
      - run: yarn run test

workflows:
  build-and-test:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build
