version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  install:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - node/install-packages:
          pkg-manager: yarn
          app-dir: ~/project/client
          override-ci-command: yarn install --frozen-lockfile --network-concurrency 1
  build:
    docker:
      - image: circleci/node:12
    steps:
      - run: yarn build
      - run: cd ../
      - run: yarn build
  test:
    docker:
      - image: circleci/node:12
    steps:
      - run: yarn run test

workflows:
  build-and-test:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build
