/**
DO NOT EDIT THIS FILE!!!!!
IT IS COPIED FROM THE ROOT src/entity FOLDER
TO UPDATE ENTITY MODEL DEFINITIONS, MAKE CHANGES TO THE FILES IN src/entity,
AND THEN RUN ./copy-models-to-client.sh FROM ROOT DIR
**/
import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  ManyToOne,
  OneToMany,
} from 'typeorm';

import { AgeGroup } from './enums/AgeGroup';
import { Child } from './Child';
import { Funding } from './Funding';
import { Site } from './Site';
import { UpdateMetaData } from './embeddedColumns/UpdateMetaData';

@Entity()
export class Enrollment {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne((type) => Child, { nullable: false })
  child: Child;

  @ManyToOne((type) => Site, { nullable: false })
  site: Site;

  @Column({ type: 'enum', enum: AgeGroup, nullable: true })
  ageGroup?: AgeGroup;

  @Column({ type: 'date', nullable: true })
  entry?: Date;

  @Column({ type: 'date', nullable: true })
  exit?: Date;

  @Column({ nullable: true })
  exitReason?: string;

  @OneToMany((type) => Funding, (funding) => funding.enrollment)
  fundings?: Array<Funding>;

  @Column((type) => UpdateMetaData, { prefix: false })
  updateMetaData?: UpdateMetaData;
}
