/**
DO NOT EDIT THIS FILE!!!!!
IT IS COPIED FROM THE ROOT src/entity FOLDER
TO UPDATE ENTITY MODEL DEFINITIONS, MAKE CHANGES TO THE FILES IN src/entity,
AND THEN RUN ./copy-models-to-client.sh FROM ROOT DIR
**/
import { Entity, Column, PrimaryGeneratedColumn, OneToMany } from 'typeorm';
import { FlattenedEnrollment } from './FlattenedEnrollment';

@Entity()
export class EnrollmentReport {
  @PrimaryGeneratedColumn()
  id: number;

  @OneToMany((type) => FlattenedEnrollment, (enrollment) => enrollment.report, {
    cascade: true,
    eager: true,
  })
  enrollments: Array<FlattenedEnrollment>;
}
