/**
DO NOT EDIT THIS FILE!!!!!
IT IS COPIED FROM THE ROOT src/entity FOLDER
TO UPDATE ENTITY MODEL DEFINITIONS, MAKE CHANGES TO THE FILES IN src/entity,
AND THEN RUN ./copy-models-to-client.sh FROM ROOT DIR
**/
import { Entity, Column, PrimaryGeneratedColumn, ManyToOne } from 'typeorm';
import { FundingSpace } from './FundingSpace';

@Entity()
export class FundingTimeSplit {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne((type) => FundingSpace, { nullable: false })
  fundingSpace: FundingSpace;

  @Column()
  fullTimeWeeks: number;

  @Column()
  partTimeWeeks: number;
}
