/**
DO NOT EDIT THIS FILE!!!!!
IT IS COPIED FROM THE ROOT src/entity FOLDER
TO UPDATE ENTITY MODEL DEFINITIONS, MAKE CHANGES TO THE FILES IN src/entity,
AND THEN RUN ./copy-models-to-client.sh FROM ROOT DIR
**/
import { Entity, PrimaryGeneratedColumn, ManyToOne, Column } from 'typeorm';

import { Enrollment } from './Enrollment';
import { ReportingPeriod } from './ReportingPeriod';
import { FundingSpace } from './FundingSpace';
import { UpdateMetaData } from './embeddedColumns/UpdateMetaData';

@Entity()
export class Funding {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne((type) => Enrollment, { nullable: false })
  enrollment: Enrollment;

  @ManyToOne((type) => FundingSpace, { nullable: false, eager: true })
  fundingSpace: FundingSpace;

  @ManyToOne((type) => ReportingPeriod, { eager: true })
  firstReportingPeriod?: ReportingPeriod;

  @ManyToOne((type) => ReportingPeriod, { eager: true })
  lastReportingPeriod?: ReportingPeriod;

  @Column((type) => UpdateMetaData, { prefix: false })
  updateMetaData?: UpdateMetaData;
}
