/**
DO NOT EDIT THIS FILE!!!!!
IT IS COPIED FROM THE ROOT src/entity FOLDER
TO UPDATE ENTITY MODEL DEFINITIONS, MAKE CHANGES TO THE FILES IN src/entity,
AND THEN RUN ./copy-models-to-client.sh FROM ROOT DIR
**/
import { Entity, PrimaryGeneratedColumn, Column, ManyToOne } from 'typeorm';

import { Family } from './Family';
import { UpdateMetaData } from './embeddedColumns/UpdateMetaData';

@Entity()
export class IncomeDetermination {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ nullable: true })
  numberOfPeople?: number;

  @Column({ nullable: true })
  income?: number;

  @Column({ nullable: true })
  determinationDate?: Date;

  @ManyToOne((type) => Family, { nullable: false })
  family: Family;

  @Column((type) => UpdateMetaData, { prefix: false })
  updateMetaData?: UpdateMetaData;
}
