/**
DO NOT EDIT THIS FILE!!!!!
IT IS COPIED FROM THE ROOT src/entity FOLDER
TO UPDATE ENTITY MODEL DEFINITIONS, MAKE CHANGES TO THE FILES IN src/entity,
AND THEN RUN ./copy-models-to-client.sh FROM ROOT DIR
**/
import { Entity, Column, PrimaryGeneratedColumn, OneToMany } from 'typeorm';

import { FundingSpace } from './FundingSpace';
import { Site } from './Site';

@Entity()
export class Organization {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @OneToMany((type) => Site, (site) => site.organization)
  sites?: Array<Site>;

  @OneToMany(
    (type) => FundingSpace,
    (fundingSpace) => fundingSpace.organization
  )
  fundingSpaces?: Array<FundingSpace>;
}
