/**
DO NOT EDIT THIS FILE!!!!!
IT IS COPIED FROM THE ROOT src/entity FOLDER
TO UPDATE ENTITY MODEL DEFINITIONS, MAKE CHANGES TO THE FILES IN src/entity,
AND THEN RUN ./copy-models-to-client.sh FROM ROOT DIR
**/
import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  ManyToOne,
  OneToMany,
} from 'typeorm';

import { Enrollment } from './Enrollment';
import { Organization } from './Organization';
import { Region } from './enums';

@Entity()
export class Site {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @Column()
  titleI: boolean;

  @Column({ type: 'enum', enum: Region })
  region: Region;

  @Column({ nullable: true })
  facilityCode?: number;

  @Column({ nullable: true })
  licenseNumber?: number;

  @Column({ nullable: true })
  naeycId?: number;

  @Column({ nullable: true })
  registryId?: number;

  @ManyToOne((type) => Organization, { nullable: false })
  organization: Organization;

  @OneToMany((type) => Enrollment, (enrollment) => enrollment.site)
  enrollments?: Array<Enrollment>;
}
