/**
DO NOT EDIT THIS FILE!!!!!
IT IS COPIED FROM THE ROOT src/entity FOLDER
TO UPDATE ENTITY MODEL DEFINITIONS, MAKE CHANGES TO THE FILES IN src/entity,
AND THEN RUN ./copy-models-to-client.sh FROM ROOT DIR
**/
export enum Region {
  East = 'East',
  NorthCentral = 'NorthCentral',
  NorthWest = 'NorthWest',
  SouthCentral = 'SouthCentral',
  SouthWest = 'SouthWest',
}
