/**
DO NOT EDIT THIS FILE!!!!!
IT IS COPIED FROM THE ROOT src/entity FOLDER
TO UPDATE ENTITY MODEL DEFINITIONS, MAKE CHANGES TO THE FILES IN src/entity,
AND THEN RUN ./copy-models-to-client.sh FROM ROOT DIR
**/
import { ManyToOne, UpdateDateColumn } from 'typeorm';
import { User } from '../User';

export class UpdateMetaData {
  @UpdateDateColumn()
  updatedAt: Date;

  @ManyToOne((type) => User, { nullable: true, eager: true })
  author?: User;
}
