import express, { json } from 'express';
import path from 'path';
import httpProxy from 'http-proxy';
import { isDevelopment } from './utils/isDevelopment';
import { RegisterRoutes } from './routes/routes';
import { handleError } from './middleware/error';
import { createConnection } from 'typeorm';

createConnection()
  .then(async () => {
    console.log('Successfully established TypeORM DB connection');

    // Instantiate the application server
    const app = express();

    // Register pre-processing middlewares
    app.use(json());

    /* Register the API middleware */
    // Add autogenerated API routes
    RegisterRoutes(app);
    // Catch exceptions throw in business logic
    app.use('/api', handleError);
    // Catch API requests that don't match any route
    app.use('/api', (_, res) => res.status(400));

    /* Register SPA-serving middlewares */
    // Serve the static files from the React app
    app.use(express.static(path.join(__dirname, '../client/build')));

    // Handles any requests that don't match the ones above
    if (!isDevelopment()) {
      // Register the fallback route to index.html
      app.get('*', (_, res) =>
        res.sendFile(path.join(__dirname, '../client/build/index.html'))
      );
    } else {
      // When in development, proxy requests to the docker container for the client
      const proxy = httpProxy.createProxy({
        target: process.env.CLIENT_URL || 'http://client:3000',
      });
      app.get('*', (req, res) => proxy.web(req, res));
    }

    const port = process.env.PORT || 3000;
    app.listen(port);

    console.log('App is listening on port ' + port);
  })
  .catch((err) => console.error('error connecting to DB with typeorm', err));
